FROM jenkins/jenkins:lts

USER root

# Installe Python3, pip et venv
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

USER jenkins
