sonar.projectKey=todo-app
sonar.projectName=Todo App Django
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/migrations/**,**/venv/**,manage.py

sonar.python.version=3
sonar.language=py

# Pour la couverture de tests
sonar.python.coverage.reportPaths=coverage.xml


# Ce fichier est la "carte d'identité" du projet pour SonarQube. Il lui dit quoi analyser, quoi ignorer, et dans quel langage.